version: '3.8'

services:
  # PHP + Laravel
  app:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: backend_app
    working_dir: /var/www
    volumes:
      - ./src/backend:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app_network

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./src/backend:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  # MySQL
  db:
    image: mysql:9
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: jose
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql_data:/var/lib/mysql
    networks:
      - app_network

  # Redis
  redis:
    image: redis:latest
    container_name: redis_cache
    networks:
      - app_network

  # Node.js (para Vue.js)
  node:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    working_dir: /app
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
